# Generated by Django 4.1 on 2022-08-30 20:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_document_taskid_alter_document_inputfile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='inputFile',
            field=models.FileField(upload_to=''),
        ),
    ]
