# Generated by Django 4.1 on 2022-08-31 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_document_inputfile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='document',
            name='taskId',
        ),
        migrations.AddField(
            model_name='document',
            name='status',
            field=models.CharField(default='processing', max_length=10),
        ),
        migrations.AlterField(
            model_name='document',
            name='inputFile',
            field=models.FileField(blank=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='document',
            name='outputFile',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
