# Generated by Django 4.1 on 2022-08-31 00:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_remove_document_taskid_document_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='inputFile',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
