version: "3.10"

services :
  django:
    build: .
    container_name: django
    command: python3 manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/user/src/csv_processor
    ports :
      - 8000:8000
    environment:
      - DEBUG=1
      - DJANGO_ALLOWED_HOSTS=localhost 127.0.0.1
      - CELERY_BACKEND=redis://redis:6379/0
    depends_on:
      - pgdb
      - redis
  celery:
    build: .
    command : celery worker --app=api --loglevel=INFO
    volumes:
      - .:usr/src/csv_processor
    depends_on:
      - django
      - redis
  pgdb:
    image: postgres
    container_name: pgdb
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    volumes:
      - pgdata:/var/lib/postgresql/data/
  redis :
    image : "redis:alpine"

volumes:
  pgdata:



    
